### ISSUE TITLE
Failed Tests

### ISSUE THREAD

**Issue by typeshige** [ntoll/workflow#1]
Python 2.6.2 on Ubuntu Jaunty.  Postgresql.
## FAIL: Doctest: workflow.tests

Traceback (most recent call last):
  File "/var/lib/python-support/python2.6/django/test/_doctest.py", line 2180, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for workflow.tests
  File "/usr/local/lib/python2.6/dist-packages/workflow/tests.py", line 1, in tests

---

File "/usr/local/lib/python2.6/dist-packages/workflow/tests.py", line 159, in workflow.tests
Failed example:
    current.state.transitions_from.all()
Expected:
    [<Transition: Revise Draft>, <Transition: Publish>]
Got:
##     [<Transition: Publish>, <Transition: Revise Draft>]

File "/usr/local/lib/python2.6/dist-packages/workflow/tests.py", line 168, in workflow.tests
Failed example:
    current.state.transitions_from.all()
Expected:
    [<Transition: Archive>]
Got:
##     [<Transition: Request Approval>]

File "/usr/local/lib/python2.6/dist-packages/workflow/tests.py", line 171, in workflow.tests
Failed example:
    d.workflow_manager.progress(my_transition, p2)
Exception raised:
    Traceback (most recent call last):
      File "/var/lib/python-support/python2.6/django/test/_doctest.py", line 1267, in __run
        compileflags, 1) in test.globs
      File "<doctest workflow.tests[68]>", line 1, in <module>
        d.workflow_manager.progress(my_transition, p2)
      File "/usr/local/lib/python2.6/dist-packages/workflow/models.py", line 585, in progress
        raise UnableToProgressWorkflow, __('Participant has insufficient'\
##     UnableToProgressWorkflow: Participant has insufficient authority to use the specified transition

File "/usr/local/lib/python2.6/dist-packages/workflow/tests.py", line 173, in workflow.tests
Failed example:
    for item in d.workflow_manager.history.all():
        print '%s by %s'%(item.note, item.participant.user.username)
Expected:
    Archive by joe
    We'll be up for a Pulitzer by joe
    A great review meeting, loved the punchline! by joe
    Request Approval by fred
    Started workflow by fred
Got:
    We'll be up for a Pulitzer by joe
    A great review meeting, loved the punchline! by joe
    Request Approval by fred
    Started workflow by fred

**Comment by ntoll** [comment]
OK... I've managed to reproduce the error exactly as specified. Looks like the doctests don't translate to postgres. Can you set your database to sqlite and confirm they all pass? I'll take a look at the doctest, but as the expected result from the python shell will be different between sqlite / postgres / whatever I'm not sure what to suggest. 

Any ideas most welcome.

**Comment by typeshige** [comment]
yes, it works with sqlite3.  does this mean workflow shouldn't be used with postgresql?

**Comment by ntoll** [comment]
OK... fixed the problem. As I thought, the order of items in query results is different between sqlite / postgres / whatever - this was breaking the doctests. So I've just added order_by to the appropriate queries to make the results consistent no matter what db backend you're using. 

I've tested it with both sqlite and postgres on Jaunty and all tests pass.

**Comment by typeshige** [comment]
I confirmed it passes all tests on my installation as well.  Thanks!!!!

This is unrelated, but have you used django-command-extension's graph_models?  It uses graphviz to make nice graphs of the models.  I thought it could be used to make diagrams of the workflow as well. 

http://www.graphviz.org/Gallery/directed/fsm.html

Do you have experience doing this and would it be useful?

**Comment by ntoll** [comment]
I've used Graphviz quite a bit in the past and have looked at using it for workflow visualisation. I've also had a look at client side graph visualisation with tools such as http://www.creativesynthesis.net/blog/projects/graph-gear/ 

To be honest there are +/- for each approach: Graphviz is definitely the better looking but would require some extra work server-side, whereas graph-gear is completely client-side _and_ open source but is flash based and not particularly user friendly. :-/

If there were a jQuery based Graphviz the problem would be solved.

**Comment by ntoll** [comment]
Actually, I've just found this project on Google code:

http://code.google.com/p/django-graphviz/

Looks like it's exactly what I need in terms of Graphviz.

**Comment by typeshige** [comment]
Nice! I hope to give that a shot too once I experiment more with workflow!!
